#!/bin/sh

#
# Script: systype
#
# Determines system type (architecture + operating system), and prints a string representing the system type.
# Adapted from dotkit, including modifications added by Broad Institute IT.
#

# Usage:
#   SYS_TYPE=`/path/to/systype`          in sh, ksh, zsh, bash
#   setenv SYS_TYPE `/path/to/systype`   in csh, tcsh

PATH=/bin:/usr/bin:/usr/sbin:/sbin
export PATH

if [ -r /etc/dotkit.config ]; then
  SYS_TYPE=`grep SYS_TYPE /etc/dotkit.config | cut -d" " -f2`
  echo $SYS_TYPE
  exit
fi

um="`uname -m | tr '[A-Z]' '[a-z]'`"
ur="`uname -r | tr '[A-Z]' '[a-z]'`"
us="`uname -s | tr '[A-Z]' '[a-z]'`"
SYS_TYPE=unknown
guess=

case "$us$um" in
  aix*) SYS_TYPE="aix_4";;
  osf*)
    case "$ur" in
      v4.*) SYS_TYPE="tru64_4";;
      v5.*) SYS_TYPE="tru64_5";;
      *) guess="tru64_5"
    esac;;
  sunos*)
    case "$ur" in
      5.10) SYS_TYPE="solaris_10_i86pc";;
			*) guess="solaris_8_s64";;
    esac;;

  darwin*i386)
    case "$ur" in
      8.*) SYS_TYPE="macos_104_i386";;
      9.*) SYS_TYPE="macos_105_i386";;
      10.*) SYS_TYPE="macos_106_i386";;
      11.*) SYS_TYPE="macos_107_i386";;
      12.*) SYS_TYPE="macos_108_i386";;
      13.*) SYS_TYPE="macos_109_i386";;
    esac;;
  darwin*x86_64)
    case "$ur" in
      8.*) SYS_TYPE="macos_104_x86_64";;
      9.*) SYS_TYPE="macos_105_x86_64";;
      10.*) SYS_TYPE="macos_106_x86_64";;
      11.*) SYS_TYPE="macos_107_x86_64";;
      12.*) SYS_TYPE="macos_108_x86_64";;
      13.*) SYS_TYPE="macos_109_x86_64";;
    esac;;
  freebsd*)
    rn=`echo $ur | sed 's/\([0-9]*\)\..*/\1/'`
    SYS_TYPE="freebsd_${rn}_${um}"
    ;;   
  linux*86*)
    dtype= rn= ar=

    # Fedora Tests
    if test -f /etc/fedora-release; then
      dtype=fedora
      rn=`sed 's/.*elease \([0-9][0-9]*\).*/\1/' /etc/fedora-release`
    # SuSE tests
    elif test -f /etc/SuSE-release; then
      if grep -i -q "enterprise" /etc/SuSE-release; then
         #dtype=sles if you want to differentiate between opensuse and SLES.
         dtype=suse
      else 
         dtype=suse
      fi
      rn=`grep VERSION /etc/SuSE-release | sed 's/.*VERSION = \([0-9]*\).*/\1/'`

    # Redhat/CentOS tests 
    # We treat CentOS == RedHat
    elif test -f /etc/redhat-release; then
#      dtype=`sed -e 's/.*[Ee]nterprise.*/rhe/' \
#                 -e 's/.*[Ll]inux.*/redhat/' /etc/redhat-release`
      dtype=redhat
      rn=`sed 's/.*elease \([0-9][0-9]*\).*/\1/' /etc/redhat-release`
    elif test -f /etc/lsb-release; then
      . /etc/lsb-release
      dtype=`echo $DISTRIB_ID | tr '[A-Z]' [a-z]`
      rn=$DISTRIB_CODENAME
    fi
    case "$um" in
      i[3456]86) ar=ia32;;
      *64) ar=x86_64;;
    esac
    if test -z "$dtype"; then
      guess="rhe_3_${ar:-unknown}"
    else
      SYS_TYPE="${dtype}_${rn:-00}_${ar:-unknown}"
    fi
    ;;
  irix*) SYS_TYPE="irix_6.5_64";;
  hp-ux*) SYS_TYPE="hpux_11";;
  cygwin*i686) SYS_TYPE="cygwin_i686";;
  cygwin*x86_64) SYS_TYPE="cygwin_x86_64";;
  *) echo "SYS_TYPE: system type unknown: $us $um $ur" >&2 ;;
esac

if test -n "$guess"; then
  echo "SYS_TYPE: system release unknown ($ur), guessing $guess" >&2
  SYS_TYPE=$guess
fi
echo $SYS_TYPE
test "$SYS_TYPE" != "unknown"
exit

------------------------------------------------------------------------
# collected results from various systems

SYS_TYPE	system-machine		release numbers
-------------	----------------	---------------

aix_4		AIX-000007074C00	3
tru64_4		OSF1-alpha		V4.0
tru64_5sc	OSF1-alpha		V5.1
redhata_6	Linux-alpha		2.4.2

solaris_8_s64	SunOS-sun4u		5.6 5.7
redhat_8_ia32	Linux-i686		2.4.18
redhat_7_ia32	Linux-i686		2.4.2 2.4.5 2.4.6 2.4.7
redhat_6_ia32	Linux-i686		2.2.19 2.2.19smp
irix_6.5_64	IRIX64-IP25		6.5
macos_10	Darwin			10.1,10.2
redhatEnt_3_x86_64  linux-x86_64        2.4.21-1.1931.2.393.entsmp
cygwin_x86_64	cygwin-x86_64		1.7.32(0.274/5/3)
