language: cpp
sudo: required
dist: bionic
compiler:
- gcc
os:
- linux
script:
- if [ $TRAVIS_OS_NAME == linux ]; then ./build.sh; fi
#- if [ $TRAVIS_OS_NAME == osx ]; then ./build.sh --with-include-dir=$OPENSSL_DIR/include --with-lib-dir=$OPENSSL_DIR/lib --llvm-config=llvm-config-3.8 --cc=clang-3.8 --cxx=clang++-3.8; fi
#after_success:
#- if [ $TRAVIS_OS_NAME == linux ]; then ./scripts/build_support.sh archive_codedb; fi
branches:
  only:
  - master
  - "/^v\\d+\\./"
env:
  global:
  - LANG="en_US.UTF-8"
